export { default as Logo } from "./logo.svg";
export { default as BurgerIcon } from "./BurgerIcon.svg";
export { default as Logo2 } from "./logo2.svg";
export { default as Logo3 } from "./logo3.svg";
export { default as SiteLogo } from "./logo4.svg";
export { default as facebook } from "./fb.svg";
export { default as instagram } from "./ins.svg";
export { default as youtube } from "./you.svg";
export { default as twitter } from "./twit.svg";
export { default as linkdin } from "./link.svg";
export { default as apple } from "./apple.svg";
export { default as playstore } from "./playstore.svg";
export { default as bg } from "./bg.png";
export { default as bg2 } from "./bg2.svg";
export { default as top } from "./top.svg";
export { default as plus } from "./plus.png";
export { default as speaker } from "./speaker.png";
export { default as review1 } from "./review1.png";
export { default as review2 } from "./review2.png";
export { default as review3 } from "./review3.png";
export { default as footerLogo } from "./footerLogo.png";
export { default as photo } from "./photo.svg";
export { default as care } from "./care.svg";
export { default as topimg1 } from "./topimg1.svg";
export { default as topimg2 } from "./topimg2.svg";
export { default as topimg3 } from "./topimg3.svg";
export { default as topimg4 } from "./topimg4.svg";
export { default as topimg5 } from "./topimg5.svg";
export { default as journey } from "./journey.svg";
export { default as connect } from "./connect.svg";
export { default as team } from "./team.svg";
export { default as teamimg1 } from "./teamimg1.svg";
export { default as teamimg2 } from "./teamimg2.svg";
export { default as teamimg3 } from "./teamimg3.svg";
export { default as teamimg4 } from "./teamimg4.svg";
export { default as teamimg } from "./teamimg.svg";
export { default as cross } from "./cross.svg";
export { default as visa } from "./visa.svg";
export { default as dellTable } from "./dellTable.svg";
export { default as sealCheck } from "./sealCheck.svg";
export { default as profileA } from "./profileA.svg";
export { default as emptyCheckbox } from "./emptyCheckbox.svg";
export { default as checkedCheck } from "./checkedCheck.svg";
export { default as gift_icon } from "./gift_icon.svg";
export { default as batchEdit } from "./batchEdit.svg";

export { default as ms } from "./ms.svg";
export { default as pipedrive } from "./pipedrive.svg";
export { default as zendesk } from "./zendesk.svg";
export { default as hubspot } from "./hubspot.svg";
export { default as salesforce } from "./salesforce.svg";
export { default as intercom } from "./intercom.svg";
export { default as imageWhy } from "./imageWhy.svg";
export { default as markit } from "./markit.svg";

export { default as lossAngles } from "./lossAngles.svg";
export { default as Islamabad } from "./Islamabad.svg";
export { default as Cebu } from "./Cebu.svg";
export { default as Cairo } from "./Cairo.svg";
export { default as Berlin } from "./Berlin.svg";
export { default as NewDelhi } from "./NewDelhi.svg";
export { default as Megaphone } from "./Megaphone.svg";
export { default as Storefront } from "./Storefront.svg";

export { default as lossimg } from "./lossimg.svg";
export { default as islamabad } from "./islamabad.jpg";
export { default as cebu } from "./cebu.jpg";
export { default as cairo } from "./cairo.jpg";
export { default as berlin } from "./berlin.jpg";
export { default as newDelhi } from "./newDelhi.jpg";

// export { default as LoginBg } from "./GardenLoginBg.png";
export { default as LoginBg } from "./GardenLoginBg.jpeg";
export { default as bgImageAuth } from "./bgImageAuth.jpeg";
export { default as LoginBg2 } from "./GardenLoginBg.png";
export { default as LoginReview1 } from "./loginReview1.png";
export { default as LoginReview2 } from "./loginReview2.png";
export { default as LoginReview3 } from "./loginReview3.png";
export { default as checkboxUnchecked } from "./checkbox_unchecked.png";
export { default as checkboxChecked } from "./checkbox_checked.png";
export { default as RadioChecked } from "./radio_checked.png";
export { default as RadioUnChecked } from "./radio_unchecked.png";
export { default as LoginSection } from "./LoginSection.png";
export { default as LoginSectionA } from "./LoginSectionA.png";

export { default as NoStatus } from "./NoStatus.svg";
export { default as NoStatusHover } from "./NoStatusHover.svg";
export { default as UnRead } from "./UnRead.svg";
export { default as UnReadHover } from "./UnReadHover.svg";
export { default as Remainder } from "./Remainder.svg";
export { default as RemainderHover } from "./RemainderHover.svg";
export { default as UnAnswered } from "./UnAnswered.svg";
export { default as UnAnsweredHover } from "./UnAnsweredHover.svg";
export { default as google } from "./google.svg";
export { default as sentMail } from "./sentMail.svg";

export { default as i_1 } from "./i_1.svg";
export { default as i_2 } from "./i_2.svg";
export { default as i_3 } from "./i_3.svg";
export { default as i_4 } from "./i_4.svg";
export { default as icon_4 } from "./icon_4.svg";
export { default as icon_3 } from "./icon_3.svg";
export { default as icon_2 } from "./icon_2.svg";
export { default as icon_1 } from "./icon_1.svg";
export { default as icon_1A } from "./icon_1A.svg";
export { default as icon_2AA } from "./icon_2AA.svg";
export { default as icon_3AA } from "./icon_3AA.svg";
export { default as icon_4AA } from "./icon_4AA.svg";
export { default as sidebar_logo } from "./sidebar_logo.png";
export { default as sidebar_logoA } from "./sidebar_logoA.svg";
export { default as zeitBlast_logo } from "./zeitBlast_logo.png";
// export { default as zeitBlast_logoA } from "./zeitBlast_logoA.png"
export { default as zeitBlast_logoA } from "./zeitBlast_logoA.svg";
export { default as sidebar_dashboard } from "./sidebar_dashboard.svg";
export { default as sidebar_dashboardA } from "./sidebar_dashboardA.svg";
export { default as sidebar_inbox } from "./sidebar_inbox.svg";
export { default as sidebar_import } from "./sidebar_import.svg";
export { default as sidebar_skip } from "./sidebar_skip.svg";
export { default as sidebar_comp } from "./sidebar_comp.svg";
export { default as sidebar_template } from "./sidebar_template.svg";
export { default as sidebar_batch } from "./sidebar_batch.svg";
export { default as sidebar_drop } from "./sidebar_drop.svg";
export { default as sidebar_recourse } from "./sidebar_recourse.svg";
export { default as sidebar_setting } from "./sidebar_setting.svg";
export { default as Admin_icon } from "./Admin_icon.svg";
export { default as My_company } from "./My_company.svg";
export { default as feedback } from "./feedback.svg";
export { default as download } from "./download.svg";
export { default as login_image } from "./login_image.png";
export { default as message_icon } from "./message_icon.svg";
export { default as phone_icon } from "./phone_icon.svg";
export { default as user_icon } from "./user_icon.svg";
export { default as total_icon } from "./total_icon.svg";

export { default as dashboardDonutGraph } from "./dashboardDonutGraph.svg";

export { default as icon_Arrow } from "./icon_Arrow.svg";

export { default as Plus } from "./Plus.svg";
export { default as Calender} from "./Calender.svg";
export { default as Topdrip} from "./Topdrip.svg";
export { default as FaInfoCircle } from "./FaInfoCircle.svg";
export { default as ArrowIcon } from "./ArrowIcon.svg";
export { default as Minus } from "./Minus.svg";

export { default as Avatar } from "./avatar.jpg";
export { default as ChevronDown } from "./chevronDown.png";

export { default as SwitchUnChecked } from "./switch_unchecked.png";
export { default as SwitchChecked } from "./switch_checked.png";

export { default as SortUpHover } from "./SortUpHover.svg";
export { default as SortDownHover } from "./SortDownHover.svg";
export { default as SortUp } from "./SortUp.svg";
export { default as SortDown } from "./SortDown.svg";
export { default as SortDefault } from "./SortDefault.png";
export { default as PageNotFound } from "./PageNotFound.svg";

export { default as GMaps } from "./gmaps.svg";
export { default as Zillow } from "./zillow.svg";
export { default as LandDetailsActive } from "./land-details-active.svg";
export { default as LandDetailsInActive } from "./land-details-inactive.svg";

export { default as tableLeft } from "./tableLeft.svg";
export { default as tableRight } from "./tableRight.svg";
