version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Add reviewers
    reviewers:
      - "chdeepakops"
  # Maintain NPM dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    # Add reviewers
    reviewers:
      - "anjumdar7864"
