const map = new Map();
map.set("Dashboard", "dashboard");
map.set("Inbox", "inbox");
map.set("Direct Import", "direct-import");
map.set("Skip Trace", "skip-trace");
map.set("Campaigns", "campaigns");
map.set("Templates", "templates");
map.set("Batches", "batches");
map.set("Drip Automations", "drip-automations");
map.set("Settings", "settings/market-lists");
map.set("Resource Center", "resource-center");
map.set("FC_Tenant", "tenant");
map.set("View_Tenant", "tenant");
map.set("Tenant", "tenant");
map.set("View_Admin User", "master_setting/Adminuser");
map.set("FC_Admin User", "master_setting/Adminuser");
map.set("View_Roles & Permissions -Admin", "master_setting/Adminuser");
map.set("FC_Roles & Permissions -Admin", "master_setting/Adminuser");
map.set("View_Roles & Permissions -Tenant", "master_setting/Adminuser");
map.set("FC_Roles & Permissions -Tenant", "master_setting/Adminuser");
map.set("View_Subscription Management", "master_setting/Adminuser");
map.set("FC_Subscription Management", "master_setting/Adminuser");
map.set("View_General", "market/General");
map.set("FC_General", "market/General");
map.set("View_New Request", "market/General");
map.set("FC_New Request", "market/General");
map.set("View_10Dlc Submission", "market/General");
map.set("FC_10Dlc Submission", "market/General");

export default map;
