const negativeKeywords = [
  "random",
  "public",
  "blue",
  "out of the blue",
  "county",
  "properties",
  "purchasing",
  "selling",
  "buyer",
  "hoping",
  "right",
  "looking",
  "investment",
  // "consider",
  "considered",
  "person",
  "not sure",
  "interested",
  "story",
  "apologies",
  "apologize",
  "covid",
  "we buy house",

  "we buy houses",
  "sell house", "house to sell", "sell home", "home to sell", "your place", "your house", "bid", "coinbase",
  "bitcoin", "request to withdraw", "email change", "block the transaction", "withdraw funds", "coinbase",
  "affiliate", "affiliates", "referral", "referrals", "bonus", "commission", "commissions", "percent",
  "percentage", "gratuity", "dividend",  "%", "i came across", "i’ve come across", "came across",
  "i cam across", "i came acros", "i cam acros", "i’ve com acros", "cam across", "came acros", "come across",
  "came accrossed", "i come across", "i drove by", "drove by", "drivin by", "was driving by", "drove past",
  "drivin past", "was passin by", "just drove by", "i was drivin by", "passed by", "came by", "came thru",
  "was around the area", "are you the owner", "is this the owner", "this is {firstname}", "correct",
  "you’re the owner right", "am i speaking with the owner", "is this your property",
  "is this still yours", "are you still the homeowner", "are you the homeowner",
  "this your place", "this still your house",
];

export default negativeKeywords;
